export const restaurantNearby = [
    {
        restaurant_id: '66956acbcbb6271cb40e4d73b7198069fc71fd1f',
        name: 'Waroeng Western',
        open_now: true,
        place_id: 'ChIJY16KBsP2aS4RduayGcvg278',
        rating: 4.2,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'western',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a569',
        name: 'Loving Hut',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.4,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'western',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a568',
        name: 'Makanan Khas Bangka Bakmie Effata',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.3,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'chinese',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a570',
        name: 'A&W Restoran Bina Nusantara',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.3,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'western',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a571',
        name: 'Crossroad Cafe',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'western',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a572',
        name: 'Bakso Super Makaliwe',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a573',
        name: 'Hoka Hoka Bento',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'chinese',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a574',
        name: 'Little Dragon',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'chinese',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a575',
        name: 'Bakso Sapi 21 Binus',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 5,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a576',
        name: 'Soto Betawi Lorong Dewi',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.1,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a577',
        name: 'Kebav Kbeev BINUS Anggrek',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 5,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'western',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a578',
        name: 'Ayam Bakar Klaten Pak Ben',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.8,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a579',
        name: "Warung Mom's Ayam Goreng Kremes",
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a580',
        name: 'Warung nasi Bude',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a581',
        name: 'Anggrek Soto',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a582',
        name: "batagor Ma'e sincan",
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a583',
        name: 'Soto Tangkar Mawued Mas Ken',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a584',
        name: 'Kwetiaw 79',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.1,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'chinese',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a585',
        name: 'Ayam Gepuk Vs Ayam Geprek',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a586',
        name: 'Kantin Ao 2 Tak',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a587',
        name: 'Rocky Friend Chicken @ Anggrek Cakra',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.8,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'western',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a588',
        name: 'Ayam Goreng Macho',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a589',
        name: 'Oku Tei Japanese Food',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 0,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'chinese',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
    {
        restaurant_id: 'f9a41814048dc5ed127bf45ccba6a015a625a590',
        name: 'Bebek Janda Rawa Belong',
        open_now: true,
        place_id: 'ChIJF1MUy8L2aS4RJqIVFdycdWI',
        rating: 4.4,
        types: [
            'restaurant',
            'food',
            'point_of_interest',
            'establishment',
            'indonesian',
        ],
        icon:
            'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
    },
]
